### ISSUE TITLE
Ethernet HAL driver definitions

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/stm32h7rsxx-hal-driver#4]
I did some comparisons between the new STM32H7RS HAL Driver V1.1.0 and STM32H7xx HAL Driver V1.11.4 and I found this:

File `stm32h7rsxx_hal_eth.h`
``` c
#define HAL_ETH_STATE_BUSY                 0x00000023U    /*!< an internal process is ongoing             */
#define HAL_ETH_STATE_STARTED              0x00000023U    /*!< an internal process is started             */
```

File `stm32h7xx_hal_eth.h`
``` c
#define HAL_ETH_STATE_BUSY                 0x00000020U    /*!< an internal process is ongoing             */
#define HAL_ETH_STATE_STARTED              0x00000040U    /*!< an internal process is started             */
```

https://github.com/STMicroelectronics/stm32h7xx-hal-driver/commit/cf89fa21345bcf6e5d0a44e34d31d043f2ab3b7f

**Comment by ASEHSTM** [comment]
Hello @carlo-dev-git,

Thank you for your report. The issue with identical values for HAL gState definitions will be addressed and fixed to align with the STM32H7xx HAL Driver.
ST Internal Reference: 198159

With Regards,

**Comment by carlo-dev-git** [comment]
Thank you ASEHSTM.

I think the `stm32h7rsxx_hal_eth.c` file should be checked as well.

See [aa891057c66d15f81ae01b2115cd96d079e6bc94](https://github.com/STMicroelectronics/stm32h7xx-hal-driver/commit/aa891057c66d15f81ae01b2115cd96d079e6bc94)

**Comment by ASEHSTM** [comment]
Yes, that has been considered.

Thank you.
With Regards,

**Comment by KRASTM** [comment]
Fixed in commit: https://github.com/STMicroelectronics/stm32h7rsxx-hal-driver/commit/7ca2e07ca21bc66b53654e845b4c85c884343b60
